// Generated by https://quicktype.io

export interface User {
  "User ID": string;
  Email: string;
  Name: string;
  profile_pic?: string;
  "HSC Year"?: string;
  "Points Earned": number;
  "Points Withdrawn": number;
  "Invite Code": string;
  "Phone Number": string;
  "Date Joined": string;
  "Total Questions Answered": number;
  "Total Questions Asked": number;
  "Points to be withdrawn": number;
}
